version: 2
jobs:
  build:
    working_directory: ~/fyords
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            pipenv run python -m pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1